/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_livequery_agent_filesystem_core_FileChangeProcessor */

#ifndef _Included_com_livequery_agent_filesystem_core_FileChangeProcessor
#define _Included_com_livequery_agent_filesystem_core_FileChangeProcessor
#ifdef __cplusplus
extern "C" {
#endif
#undef com_livequery_agent_filesystem_core_FileChangeProcessor_MAX_SIZE
#define com_livequery_agent_filesystem_core_FileChangeProcessor_MAX_SIZE 4096L
/*
 * Class:     com_livequery_agent_filesystem_core_FileChangeProcessor
 * Method:    dpoll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_livequery_agent_filesystem_core_FileChangeProcessor_dpoll
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
